# Generated by Django 5.0 on 2025-06-27 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_remove_team_active_remove_team_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
