# Generated by Django 5.0 on 2025-06-27 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_invitation_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_team_name_per_owner'),
        ),
    ]
