# Generated by Django 5.0 on 2025-06-27 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_alter_team_options_team_unique_team_name_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
