# Generated by Django 5.0 on 2025-07-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskills',
            unique_together={('user', 'skill')},
        ),
    ]
