# Generated by Django 5.0 on 2025-02-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
        ('users', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
    ]
