# Generated by Django 5.0 on 2025-02-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='deployment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
