# Generated by Django 5.0 on 2025-02-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_pass',
            field=models.BooleanField(default=False),
        ),
    ]
