# Generated by Django 5.0 on 2025-02-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_submission_is_pass_submission_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='failed_test_index',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
