# Generated by Django 5.0 on 2025-02-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_submission_failed_test_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='project',
            field=models.ForeignKey(default=1048313788554510337, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project'),
            preserve_default=False,
        ),
    ]
