# Generated by Django 5.0 on 2025-06-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_submission_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tests',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(help_text='The Python code for this test case.')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='projects.task')),
            ],
        ),
    ]
