# Generated by Django 5.0 on 2025-06-22 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_task_tests_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='code',
        ),
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: A more detailed explanation of what this test verifies.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='name',
            field=models.CharField(default='test case name', help_text="A human-readable name for the test, e.g., 'Test for 404 on non-existent task'.", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='points',
            field=models.PositiveSmallIntegerField(default=5, help_text='How many points this test is worth.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='stop_on_failure',
            field=models.BooleanField(default=False, help_text='If true, the test run will stop if this case fails.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('API_REQUEST', 'API Request & Response'), ('JSON_VALIDATION', 'JSON Structure Validation')], default='API_REQUEST', max_length=50),
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('test_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='api_details', serialize=False, to='projects.testcase')),
                ('request_payload', models.JSONField(blank=True, help_text='JSON body to send with the request (for POST, PUT).', null=True)),
                ('request_headers', models.JSONField(blank=True, help_text='JSON object of headers to send.', null=True)),
                ('expected_status_code', models.PositiveSmallIntegerField(help_text='The expected HTTP status code, e.g., 200, 201, 404.')),
                ('expected_response_schema', models.JSONField(blank=True, help_text='Optional: A JSON schema to validate the response structure against.', null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.endpoint')),
            ],
        ),
    ]
