# Generated by Django 5.0 on 2025-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_testcase_code_testcase_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='testcase',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Execution order of the test (e.g., 0, 1, 2...). Tests run in ascending order.'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('task', 'order'), name='unique_order_per_task'),
        ),
    ]
