# Generated by Django 5.0 on 2025-06-25 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_remove_task_unique_order_per_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
