# Generated by Django 5.0 on 2025-06-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_teamproject_options_teamproject_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, help_text='Code submitted by the user.', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('go', 'Go'), ('cpp', 'C++'), ('javascript', 'JavaScript'), ('java', 'Java'), ('c', 'C'), ('rust', 'Rust'), ('ruby', 'Ruby'), ('php', 'PHP'), ('csharp', 'C#')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='command_args',
            field=models.JSONField(default=list, help_text='Command line arguments'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected console output'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, help_text='Input data for console application'),
        ),
    ]
