# Generated by Django 5.0 on 2025-06-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_submission_code_submission_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='command_args',
            field=models.JSONField(blank=True, default=list, help_text='Command line arguments', null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(choices=[('API_REQUEST', 'API Request & Response'), ('JSON_VALIDATION', 'JSON Structure Validation'), ('CONSOLE_APPLICATION', 'Console Application')], default='API_REQUEST', max_length=50),
        ),
    ]
