# Generated by Django 5.0 on 2025-07-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_project_created_by_project_is_public_projectdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
