# Generated by Django 5.0 on 2025-07-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_testcase_command_args_alter_testcase_test_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reference_images/')),
                ('viewport_width', models.PositiveIntegerField(default=1920)),
                ('viewport_height', models.PositiveIntegerField(default=1080)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='projects.task')),
            ],
            options={
                'verbose_name': 'Project Reference Image',
                'verbose_name_plural': 'Project Reference Images',
            },
        ),
        migrations.CreateModel(
            name='ScreenshotComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('comparison_image', models.ImageField(blank=True, null=True, upload_to='comparison_results/')),
                ('feedback_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('team_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_comparisons', to='projects.teamproject')),
                ('reference_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.taskreferenceimage')),
            ],
            options={
                'verbose_name': 'Screenshot Comparison',
                'verbose_name_plural': 'Screenshot Comparisons',
            },
        ),
    ]
