# Generated by Django 5.0 on 2025-07-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectdraft_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdraft',
            name='name',
            field=models.CharField(blank=True, default='New Project Draft', max_length=255, null=True),
        ),
    ]
