services:

  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A CareerShip worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis
      - django
    
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8080:8001"
    env_file:
      - ./.env
    restart: unless-stopped
volumes:
    careershipdb:
