services:
  db:
    image: postgres:17.2
    volumes:
      - careershipdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - "5435:5432"
    env_file:
      - ./.env
    restart: unless-stopped


  django:
      build: .
      volumes:
        - .:/code
      ports:
        - "8000:8001"
      depends_on:
        - db
      env_file:
        - ./.env
      restart: unless-stopped

volumes:
    careershipdb:
