services:
  db:
    image: postgres:17.2
    volumes:
      - careershipdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: postgres -c port=${DB_PORT}
    env_file:
      - ./.env
    restart: unless-stopped

  redis:
    image: redis:7.0
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A CareerShip worker --loglevel=info
    restart: unless-stopped
    depends_on:
      - redis
      - django
    
  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8001"
#    depends_on:
#      - db
    env_file:
      - ./.env
    restart: unless-stopped
volumes:
    careershipdb:
