services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: careership
      POSTGRES_USER: app
      POSTGRES_PASSWORD: postgresql
    volumes:
      - careershipdb:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    env_file:
      - ./.env
    restart: unless-stopped

volumes:
    careershipdb:
