# Generated by Django 5.0 on 2025-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.UUIDField(unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
