name: Deploy to EC2 on Prod Push

# Trigger the workflow on pushes to the 'prod' branch
on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Execute the deployment script on the server
            /home/admin/CareerShip/deploy.sh
